title: Ryan Barkman
logo: "C:\Users\Ryan\Documents\Life\Photos\Ryan1.jpg"
description: Computer Science Student, Specialty in Game Engineering, Sheridan College. Looking for Co-op work.
theme: jekyll-theme-tactile
